#!/bin/sh
cd /
pwd
cd ..
cd ..
cd ..
cd home
cd ubuntu
pwd
alias proj="cd new-app"
pwd
ls
cd vin-decoder

pwd
cd ..

cd new-app
pwd
proj
 pwd
 git pull origin main
 npm install
 forever start index.js
 exit
EOF